q1

In [1]:
import numpy as np

arr=np.array([10,20,30,40,50])
narr=arr+2
print(narr)
narr=arr*3
print(narr)
narr=arr/2
print(narr)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


q2

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
narr=np.flip(arr)
print(narr)

x = np.array([1,2,3,4,5,1,2,1,1,1])
freq=np.bincount(x)
print(freq)
most_freq_val=freq.argmax()
print("Most frequent value is: "+str(most_freq_val))
indices=np.where(x==most_freq_val)[0]
print(indices)

y= np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique,counts=np.unique(y,return_counts=True)
print(unique)
print(counts)
most_freq_val=unique[np.argmax(counts)]
print(most_freq_val)

indices=np.where(y==most_freq_val)[0]
print(indices)

[5 4 6 3 2 1]
[0 5 2 1 1 1]
Most frequent value is: 1
[0 5 7 8 9]
[1 2 3 4]
[3 2 3 2]
1
[0 1 2]


q3

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0][1])


print(arr[2][0])

20
70


q4

In [4]:
import numpy as np

array=np.linspace(10,100,num=25)

print(array)

print(np.shape(array))

print(np.count_nonzero(array))

print(np.size(array))

print(array.dtype)

print(array.nbytes)

print(array.reshape(np.size(array),1))

print(array.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


q5

In [5]:
import numpy as np
ucs420_ = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print(ucs420_.mean()) #mean
# finding median
print(np.median(ucs420_))
print(ucs420_.max())# max
print(ucs420_.min()) # min
print(np.unique(ucs420_)) #unique

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]


In [6]:
import numpy as np
reshaped_ucs420_ = ucs420_.reshape((4,3))
print('Reshaped: ',reshaped_ucs420_)

resized_ucs420_ = np.resize(ucs420_,(2,3))
print('Resized: ',resized_ucs420_)

Reshaped:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:  [[10 20 30]
 [40 50 60]]
